---
# handlers file for nginx

- name: Check HTTP Service
  uri:
    url: http://{{ ansible-tower_default_ipv4.address }}
    status_code: 200

- name: Reload Firewall
  service:
    name: firewalld
    state: reloaded
