---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: false

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Create a security group in AWS for SSH access and HTTP
      ec2_group:
         name: ansible-tower
         description: Ansible Security Group
         region: us-east-1
         rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
         key_name: dhans1
         group: ansible-tower
         instance_type: t2.micro
         image: ami-a1f5e4c5
         region: us-east-1
         wait: true
         exact_count: 2
         count_tag:
            Name: AnsibleNginxWebservers
         instance_tags:
            Name: Ansible
      ignore_errors: true

    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory

-

  # Target: where our play will run and options it will run with
  hosts: tag_Name_Ansible

  # Roles: list of roles to be imported into the play
  roles:
    - awesomeweb

-

  # Target: where our play will run and options it will run with
  hosts: tag_Name_Ansible

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - debug:
        msg: "Check http://{{ ansible_host }}"

    - pause:
        prompt: "Verify service availability and continue to terminate"

    - name: Remove tagged EC2 instances from security group by setting an empty group
      ec2:
        state: running
        region: "{{ ec2_region }}"
        instance_ids: "{{ ec2_id }}"
        group_id: ""
      delegate_to: localhost
      
    - name: Terminate EC2 instances
      ec2:
        state: absent
        region: "{{ ec2_region }}"
        instance_ids: "{{ ec2_id }}"
        wait: true
      delegate_to: localhost

- 

  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  - name: Remove ansible-tower security group
    ec2_group:
      name: ansible-tower
      region: us-east-1
      state: absent

# Three dots indicate the end of a YAML document
...
